# Site settings
title: Voormezele
email: cuvelierklaas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Informatie over Voormezele.be
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://0.0.0.0:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
