---
title: Voormezele
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: cuvelierklaas@gmail.com
description: |
  Informatie over Voormezele.be
baseurl: ''
url: http://voormezele.github.io
markdown: kramdown
