# Site settings
title: Voormezele
email: cuvelierklaas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Informatie over Voormezele.be
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://voormezele.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
